application: vulgusapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /api/1/.*
  script: main.app
  secure: always


# Tasks
- url: /t/.*
  script: server_tasks.app


# Others
libraries:
- name: webapp2
  version: "2.5.1"
